using Kontent.Ai.ModelGenerator.Core.Helpers;
using Microsoft.CodeAnalysis.CSharp;

namespace Kontent.Ai.ModelGenerator.Core.Tests.Helpers;

public class ClassDeclarationHelperTests
{
    // A missing argument and a blank one are different mistakes: null is ArgumentNullException, a value
    // that is present but empty is ArgumentException. The guard used to report both as the former.
    [Fact]
    public void GenerateSyntaxTrivia_CustomCommentIsNullOrWhiteSpace_Null_ThrowsArgumentNullException()
    {
        var act = () => ClassDeclarationHelper.GenerateSyntaxTrivia(null!);

        act.Should().ThrowExactly<ArgumentNullException>();
    }

    [Theory]
    [InlineData("")]
    [InlineData(" ")]
    public void GenerateSyntaxTrivia_CustomCommentIsNullOrWhiteSpace_Blank_ThrowsArgumentException(string customComment)
    {
        var act = () => ClassDeclarationHelper.GenerateSyntaxTrivia(customComment);

        act.Should().ThrowExactly<ArgumentException>();
    }

    [Theory]
    [InlineData("some comment")]
    [InlineData("//some comment")]
    public void GenerateSyntaxTrivia_CustomCommentIsNotComment_Throws(string customComment)
    {
        var call = () => ClassDeclarationHelper.GenerateSyntaxTrivia(customComment);

        call.Should()
            .Throw<ArgumentException>();
    }

    [Fact]
    public void GenerateSyntaxTrivia_Returns()
    {
        var customComment = "// custom comment";

        var expected = SyntaxFactory.Comment(@$"// <auto-generated>
// This code was generated by Kontent.ai model generator tool
// (see https://github.com/kontent-ai/dotnet/tree/main/src/model-generator).
//
// custom comment
// </auto-generated>{Environment.NewLine}{Environment.NewLine}");

        var result = ClassDeclarationHelper.GenerateSyntaxTrivia(customComment);
        var isEqual = result.IsEquivalentTo(expected);

        isEqual.Should().BeTrue();
    }
}
