using Kontent.Ai.ModelGenerator.Core.Common;
using Kontent.Ai.ModelGenerator.Core.Helpers;

namespace Kontent.Ai.ModelGenerator.Core.Tests.Helpers;

public class TextHelpersTests
{
    [Fact]
    public void GetValidPascalCaseIdentifierName_ThrowsAnExceptionForNullValue()
    {
        var getValidPascalCaseIdentifierNameCall = () => TextHelpers.GetValidPascalCaseIdentifierName(null!);

        getValidPascalCaseIdentifierNameCall.Should().ThrowExactly<ArgumentNullException>();
    }

    [Theory]
    [InlineData("")]
    [InlineData("  ")]
    [InlineData("-")]
    [InlineData("$^123")]
    public void GetValidPascalCaseIdentifierName_ThrowsAnExceptionForInvalidInput(string name)
    {
        var getValidPascalCaseIdentifierNameCall = () => TextHelpers.GetValidPascalCaseIdentifierName(name);

        getValidPascalCaseIdentifierNameCall.Should().ThrowExactly<InvalidIdentifierException>();
    }

    [Theory]
    [InlineData("Simple name", "SimpleName")]
    [InlineData("Name with special chars & multiple    spaces.", "NameWithSpecialCharsMultipleSpaces")]
    [InlineData("EVERYTHING_IS_ -UPPERCASE", "EverythingIsUppercase")]
    [InlineData("date___time_field", "DateTimeField")]
    [InlineData("Multiline\r\nstring", "MultilineString")]
    [InlineData(" 1 2 3 Starts with space and numbers", "StartsWithSpaceAndNumbers")]
    [InlineData("ends with numbers 1 2 3", "EndsWithNumbers123")]
    public void GetValidPascalCaseIdentifierName_Returns(string name, string expected)
    {
        var result = TextHelpers.GetValidPascalCaseIdentifierName(name);

        result.Should().Be(expected);
    }

    // A missing argument and a blank one are different mistakes: null is ArgumentNullException, a value
    // that is present but empty is ArgumentException. The guard used to report both as the former.
    [Fact]
    public void GenerateCommentString_CustomCommentIsNullOrEmptyOrWhiteSpace_Null_ThrowsArgumentNullException()
    {
        var act = () => TextHelpers.GenerateCommentString(null!);

        act.Should().ThrowExactly<ArgumentNullException>();
    }

    [Theory]
    [InlineData("")]
    [InlineData(" ")]
    public void GenerateCommentString_CustomCommentIsNullOrEmptyOrWhiteSpace_Blank_ThrowsArgumentException(string customComment)
    {
        var act = () => TextHelpers.GenerateCommentString(customComment);

        act.Should().ThrowExactly<ArgumentException>();
    }

    [Fact]
    public void GenerateCommentString_Returns()
    {
        var customComment = "// custom comment";

        var expectedComment =
            @$"// <auto-generated>
// This code was generated by Kontent.ai model generator tool
// (see https://github.com/kontent-ai/dotnet/tree/main/src/model-generator).
//
// custom comment
// </auto-generated>{Environment.NewLine}{Environment.NewLine}";

        var result = TextHelpers.GenerateCommentString(customComment);

        result.Should().Be(expectedComment);
    }

}
