using Kontent.Ai.Management.Configuration;
using Kontent.Ai.Management.Models.Content;
using Kontent.Ai.Management.Models.LanguageVariants;
using Kontent.Ai.Management.Models.LanguageVariants.Elements;
using Kontent.Ai.Management.Serialization;
using System.Collections;
using System.Text.Json;

namespace Kontent.Ai.Management.Conversion;

/// <summary>
/// Translates between generated content-type records (implementing <see cref="IElementsModel"/>) and the MAPI
/// language-variant <c>elements</c> wire shape — an array of envelopes of the form
/// <c>{ "element": { "codename" | "id": "..." }, "value": &lt;kind-specific&gt;, "components": [...] }</c>.
/// </summary>
/// <remarks>
/// <para>
/// <b>Write direction</b> produces the element records an upsert model carries, keyed by element <em>codename</em>
/// (what MAPI accepts on POST/PUT). Properties whose value is <c>null</c> are skipped — partial-update semantics,
/// matching the migration / scripted-write usage we expect to be the dominant consumer.
/// </para>
/// <para>
/// <b>Read direction</b> matches envelopes by element <em>id</em> first (what MAPI returns), falling back to codename
/// if the response is codename-keyed. Unknown elements in the response are skipped — forward-compat with future MAPI
/// changes — but a response in which nothing matches is refused, since that is a record for another content type or
/// another environment rather than a newer API.
/// </para>
/// <para>
/// <b>Environment binding.</b> The read path resolves rich-text component types by id (MAPI returns component types by
/// id only — no codename on the wire). Ids are environment-specific: stable within an app-clone lineage, regenerated by
/// API-managed clones. Typed read therefore assumes the generated models carry the ids of the environment being read.
/// Writes stay portable because they key off codenames.
/// </para>
/// <para>
/// Thread-safe; intended to be shared across calls. Reflection cost is paid once per content type
/// (cached in <see cref="ContentItemTypeDescriptor"/>); each conversion allocates only its output list plus a list
/// per collection-valued property.
/// </para>
/// </remarks>
internal sealed class ContentItemEnvelopeConverter
{
    private readonly ContentTypeRegistry _registry;
    private readonly JsonSerializerOptions _scalarOptions;

    public ContentItemEnvelopeConverter(ContentTypeRegistry? registry = null, JsonSerializerOptions? scalarOptions = null)
    {
        _registry = registry ?? new ContentTypeRegistry();
        _scalarOptions = scalarOptions ?? RefitSettingsProvider.CreateDefaultJsonSerializerOptions();
    }

    /// <summary>The content-type registry this converter resolves rich-text components through (by type id on read).</summary>
    public ContentTypeRegistry Registry => _registry;

    // ---- Write direction ----

    /// <summary>
    /// Turns <paramref name="item"/>'s <c>[KontentElement]</c> properties into the element records an upsert model
    /// carries; a <c>null</c> property is omitted.
    /// </summary>
    public IReadOnlyList<BaseElement> ToElements(IElementsModel item)
    {
        ArgumentNullException.ThrowIfNull(item);

        var descriptor = ContentItemTypeDescriptor.For(item.GetType());
        var elements = new List<BaseElement>(descriptor.Properties.Count);

        foreach (var prop in descriptor.Properties)
        {
            if (prop.Property.GetValue(item) is not { } value) continue;

            elements.Add(ToElement(Reference.ByCodename(prop.ElementCodename), prop, value));
        }

        return elements;
    }

    private BaseElement ToElement(Reference element, ContentItemPropertyDescriptor prop, object value)
        => prop.Kind switch
        {
            ElementKind.Text => new TextElement { Element = element, Value = (string)value },
            ElementKind.Number => new NumberElement { Element = element, Value = (decimal)value },
            ElementKind.DateTime => ToDateTimeElement(element, (DateTimeValue)value),
            // A server-derived slug carries no value; mode is always sent so the server knows which it is.
            ElementKind.UrlSlug => new UrlSlugElement { Element = element, Value = ((UrlSlugValue)value).Value, Mode = ((UrlSlugValue)value).Mode },
            ElementKind.Custom => new CustomElement { Element = element, Value = ((CustomValue)value).Value, SearchableValue = ((CustomValue)value).SearchableValue },
            ElementKind.MultipleChoice => new MultipleChoiceElement { Element = element, Value = ToOptionReferences(prop, value) },
            ElementKind.Asset => new AssetElement { Element = element, Value = [.. (IEnumerable<AssetReference>)value] },
            // Taxonomy, linked items and subpages share one wire shape and one property type, so the record
            // cannot say which; the element that carries a value as-is is the honest choice.
            ElementKind.Reference => new DynamicElement { Element = element, Value = ((IEnumerable<Reference>)value).ToList() },
            ElementKind.RichText => ToRichTextElement(element, (RichTextValue)value),
            _ => throw new NotSupportedException($"Unknown element kind: {prop.Kind}"),
        };

    private static DateTimeElement ToDateTimeElement(Reference element, DateTimeValue dateTime)
        => new()
        {
            Element = element,
            // The API stores a UTC instant with the zone carried separately in display_timezone; the element's
            // converter writes the "Z" form the API returns rather than a numeric offset.
            Value = dateTime.Value,
            DisplayTimeZone = dateTime.DisplayTimeZone,
        };

    private static List<Reference> ToOptionReferences(ContentItemPropertyDescriptor prop, object value)
    {
        var enumDescriptor = EnumDescriptor.For(prop.CollectionElementType!);
        var values = prop.IsSingleChoice ? new[] { value } : (IEnumerable)value;
        var references = new List<Reference>();

        foreach (var option in values)
        {
            if (!enumDescriptor.CodenameByValue.TryGetValue(option, out var codename))
            {
                throw new InvalidOperationException(
                    $"Enum value '{option}' on '{prop.Property.DeclaringType?.Name}.{prop.Property.Name}' has no [KontentEnumValue] mapping.");
            }
            references.Add(Reference.ByCodename(codename));
        }

        return references;
    }

    private RichTextElement ToRichTextElement(Reference element, RichTextValue value)
    {
        var components = value.Components?.Count > 0
            ? value.Components.Select(ToComponentModel).ToList()
            : null;

        return new RichTextElement { Element = element, Value = value.Value, Components = components };
    }

    private ComponentModel ToComponentModel(Component component)
    {
        var descriptor = ContentItemTypeDescriptor.For(component.Content.GetType());

        return new ComponentModel
        {
            Id = component.Id,
            Type = Reference.ByCodename(descriptor.ContentTypeCodename),
            Elements = ToElements(component.Content),
        };
    }

    // ---- Read direction ----

    /// <summary>Reads a JSON envelopes array into a new instance of <paramref name="contentType"/>.</summary>
    public IElementsModel ReadEnvelopes(JsonElement envelopesArray, Type contentType)
    {
        if (envelopesArray.ValueKind != JsonValueKind.Array)
        {
            throw new ArgumentException($"Expected a JSON array, got {envelopesArray.ValueKind}.", nameof(envelopesArray));
        }
        return ReadEnvelopes(envelopesArray.EnumerateArray().Select(Envelope.FromJson), contentType);
    }

    /// <summary>Reads a fetched variant's elements (typically <see cref="DynamicElement"/>s) into a new <typeparamref name="T"/>.</summary>
    public T ReadEnvelopes<T>(IEnumerable<BaseElement> elements) where T : IElementsModel
    {
        ArgumentNullException.ThrowIfNull(elements);
        return (T)ReadEnvelopes(elements.Select(FromElement), typeof(T));
    }

    private IElementsModel ReadEnvelopes(IEnumerable<Envelope> envelopes, Type contentType)
    {
        ArgumentNullException.ThrowIfNull(contentType);

        // Auto-register the root type itself so it is resolvable by id on recursive descent (a root type can recur as
        // its own rich-text component). Other candidate types (those that may appear as embedded components) are
        // registered by the caller via ContentTypeRegistry.Scan — this primitive stays off the assembly-reflection
        // path and leaves registration scope to the caller.
        _registry.EnsureRegistered(contentType);

        var descriptor = ContentItemTypeDescriptor.For(contentType);
        var instance = (IElementsModel)Activator.CreateInstance(contentType)!;
        var seen = 0;
        var matched = 0;

        foreach (var envelope in envelopes)
        {
            seen++;
            var prop = ResolveProperty(descriptor, envelope);
            if (prop is null) continue;

            matched++;
            if (envelope.Value is not { } valueElement) continue;

            try
            {
                var value = ReadValue(valueElement, prop, envelope);
                prop.Property.SetValue(instance, value);
            }
            // Kind-mismatch failures from JsonElement accessors say what was wrong but not where — add the element.
            // The converter's own curated errors (multiple choice, components) already carry it and pass through.
            // STJ's InvalidOperationExceptions are told apart from ours by their exception Source, which starts with
            // the System.Text.Json assembly name; if that marker ever changes, the failure merely surfaces unwrapped.
            catch (Exception ex) when (ex is JsonException or FormatException or KeyNotFoundException
                || (ex is InvalidOperationException && ex.Source?.StartsWith("System.Text.Json", StringComparison.Ordinal) is true))
            {
                throw new InvalidOperationException(
                    $"Failed to read element '{prop.ElementCodename}' on '{contentType.Name}'.", ex);
            }
        }

        // An element the record does not know is skipped, so a newer API cannot break a read. All of them unknown
        // is different: that is a variant of another content type, or a record generated against another
        // environment, and an empty record would pass it off as content.
        if (seen > 0 && matched == 0 && descriptor.Properties.Count > 0)
        {
            throw new InvalidOperationException(
                $"None of the {seen} elements in the response match a [KontentElement] on '{contentType.Name}'. " +
                "The variant belongs to a different content type, or the record's element ids come from another environment.");
        }

        return instance;
    }

    /// <summary>
    /// One element as read: which element it is, its value, and the sibling fields beside the value. A fetched
    /// variant arrives as <see cref="DynamicElement"/>s whose value and siblings are already <see cref="JsonElement"/>s,
    /// so nothing is serialized again on the way in; anything else is serialized once to get there.
    /// </summary>
    private readonly record struct Envelope(string? Id, string? Codename, JsonElement? Value, Func<string, JsonElement?> Sibling)
    {
        public static Envelope FromJson(JsonElement envelope)
        {
            string? id = null;
            string? codename = null;
            if (envelope.TryGetProperty("element", out var meta))
            {
                meta.TryGetStringProperty("id", out id);
                meta.TryGetStringProperty("codename", out codename);
            }

            var value = envelope.TryGetProperty("value", out var valueElement) ? valueElement : (JsonElement?)null;
            return new Envelope(id, codename, value, name => envelope.TryGetProperty(name, out var sibling) ? sibling : null);
        }
    }

    private Envelope FromElement(BaseElement element)
    {
        if (element is DynamicElement { Value: null or JsonElement } dynamic)
        {
            var value = dynamic.Value is JsonElement json ? json : (JsonElement?)null;
            return new Envelope(
                dynamic.Element.Id?.ToString(),
                dynamic.Element.Codename,
                value,
                name => dynamic.AdditionalData is { } data && data.TryGetValue(name, out var sibling) ? sibling : null);
        }

        return Envelope.FromJson(JsonSerializer.SerializeToElement(element, element.GetType(), _scalarOptions));
    }

    private object? ReadValue(JsonElement value, ContentItemPropertyDescriptor prop, Envelope envelope)
    {
        if (value.ValueKind == JsonValueKind.Null) return null;

        return prop.Kind switch
        {
            ElementKind.Text => value.GetString(),
            ElementKind.Number => value.GetDecimal(),
            ElementKind.DateTime => new DateTimeValue
            {
                Value = value.GetDateTimeOffset(),
                DisplayTimeZone = envelope.Sibling("display_timezone") is { ValueKind: JsonValueKind.String } tz ? tz.GetString() : null,
            },
            ElementKind.UrlSlug => new UrlSlugValue
            {
                Value = value.GetString(),
                Mode = envelope.Sibling("mode") is { ValueKind: JsonValueKind.String } mode
                    ? mode.Deserialize<UrlSlugMode>(_scalarOptions)
                    : default,
            },
            ElementKind.Custom => new CustomValue
            {
                Value = value.GetString(),
                SearchableValue = envelope.Sibling("searchable_value") is { ValueKind: JsonValueKind.String } searchable ? searchable.GetString() : null,
            },
            ElementKind.MultipleChoice => ReadMultipleChoice(value, prop),
            ElementKind.Asset or ElementKind.Reference => value.Deserialize(prop.Property.PropertyType, _scalarOptions),
            ElementKind.RichText => ReadRichText(value, envelope),
            _ => throw new NotSupportedException($"Unknown element kind: {prop.Kind}"),
        };
    }

    private static object? ReadMultipleChoice(JsonElement value, ContentItemPropertyDescriptor prop)
    {
        var enumType = prop.CollectionElementType!;
        var enumDescriptor = EnumDescriptor.For(enumType);
        var listType = typeof(List<>).MakeGenericType(enumType);
        var list = (IList)Activator.CreateInstance(listType)!;

        foreach (var entry in value.EnumerateArray())
        {
            object? member = null;
            if (entry.TryGetStringProperty("id", out var id))
            {
                enumDescriptor.ByItemId.TryGetValue(id, out member);
            }
            if (member is null && entry.TryGetStringProperty("codename", out var codename))
            {
                enumDescriptor.ByCodename.TryGetValue(codename, out member);
            }
            if (member is null)
            {
                // Skipping instead would silently deselect the option on the next upsert of the read model.
                throw new InvalidOperationException(
                    $"Multiple-choice option {entry.GetRawText()} on '{prop.Property.DeclaringType?.Name}.{prop.Property.Name}' " +
                    $"has no matching [KontentEnumValue] member on '{enumType.Name}'. Regenerate the model if the type's options changed.");
            }
            list.Add(member);
        }

        if (!prop.IsSingleChoice) return list;

        // A single-choice element is one option or none; the wire carries it as an array either way.
        return list.Count == 0 ? null : list[0];
    }

    private RichTextValue ReadRichText(JsonElement valueElement, Envelope envelope)
    {
        var html = valueElement.GetString()!;

        List<Component>? components = null;
        if (envelope.Sibling("components") is { ValueKind: JsonValueKind.Array } componentsArray
            && componentsArray.GetArrayLength() > 0)
        {
            components = new List<Component>(componentsArray.GetArrayLength());
            foreach (var componentElem in componentsArray.EnumerateArray())
            {
                components.Add(ReadComponent(componentElem));
            }
        }

        return new RichTextValue { Value = html, Components = components };
    }

    private Component ReadComponent(JsonElement componentElem)
    {
        if (!componentElem.TryGetProperty("id", out var idProp)
            || idProp.ValueKind != JsonValueKind.String
            || !idProp.TryGetGuid(out var id))
        {
            throw new InvalidOperationException(
                "Rich-text component is missing its id. Each component in a Management API response carries a GUID id; " +
                "an entry without one cannot be projected onto a generated record.");
        }

        if (!componentElem.TryGetProperty("type", out var typeRef)
            || !typeRef.TryGetProperty("id", out var typeIdProp)
            || typeIdProp.ValueKind != JsonValueKind.String)
        {
            throw new InvalidOperationException(
                "Rich-text component is missing its content type id. The Management API references component types by id; " +
                "a response without one cannot be projected onto a generated record.");
        }

        var typeId = typeIdProp.GetString()!;
        var contentType = _registry.ResolveById(typeId)
            ?? throw new InvalidOperationException(
                $"Rich-text component references content type id '{typeId}', which is not registered. The model's " +
                "[KontentType] must carry this id, and its assembly must be scanned via ContentTypeRegistry before reading.");

        var elements = componentElem.GetProperty("elements");
        var content = ReadEnvelopes(elements, contentType);

        return new Component { Id = id, Content = content };
    }

    private static ContentItemPropertyDescriptor? ResolveProperty(ContentItemTypeDescriptor descriptor, Envelope envelope)
    {
        if (envelope.Id is { } id && descriptor.ByElementId.TryGetValue(id, out var byId))
        {
            return byId;
        }
        if (envelope.Codename is { } codename && descriptor.ByElementCodename.TryGetValue(codename, out var byCodename))
        {
            return byCodename;
        }
        return null;
    }
}
