namespace Kontent.Ai.Management.Models.Content;

/// <summary>
/// How a url_slug element's value is determined.
/// </summary>
public enum UrlSlugMode
{
    /// <summary>The slug is derived by the server from its source element. Default.</summary>
    [JsonStringEnumMemberName("autogenerated")]
    Autogenerated,

    /// <summary>The slug is set explicitly by the caller.</summary>
    [JsonStringEnumMemberName("custom")]
    Custom,
}
