// <auto-generated>
// This code was generated by Kontent.ai model generator tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To extend this record, create a separate partial record with the same name.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using Kontent.Ai.Management;
using Kontent.Ai.Management.Annotations;
using Kontent.Ai.Management.Models.Content;

namespace MyProject.Models;

[KontentType("banner", "b7a6f1c2-3d4e-5f60-8a71-b2c3d4e5f608")]
public sealed partial record Banner : IElementsModel
{
    [KontentElement("headline", "c1d2e3f4-a5b6-5c7d-8e9f-a0b1c2d3e4f5")]
    public string? Headline { get; init; }
    [KontentElement("tone", "d2e3f4a5-b6c7-5d8e-9f0a-b1c2d3e4f5a6")]
    public BannerTone? Tone { get; init; }
}

public enum BannerTone
{
    [KontentEnumValue("light", "e3f4a5b6-c7d8-5e9f-0a1b-c2d3e4f5a6b7")]
    Light,
    [KontentEnumValue("dark", "f4a5b6c7-d8e9-5f0a-1b2c-d3e4f5a6b7c8")]
    Dark
}
