using System.Collections;
using System.Text.RegularExpressions;
using Kontent.Ai.ModelGenerator.Core.Common;

namespace Kontent.Ai.ModelGenerator.Core.Helpers;

public static class TextHelpers
{
    // Codenames come from the environment's content model, so they are external input to the
    // generator. The patterns below are simple, but "^(\s|[0-9])+" nests an alternation inside a
    // quantifier - the shape that backtracks badly - and a generator that hangs on one bad
    // codename is worse than one that throws.
    private static readonly TimeSpan RegexTimeout = TimeSpan.FromSeconds(1);
    private static readonly Regex LineEndings = new(@"\r\n|\n\r|\n|\r", RegexOptions.None, RegexTimeout);
    private const string WordSeparator = " ";

    /// <summary>
    /// Returns a valid CSharp Identifier in a Pascal Case format for given string.
    /// </summary>
    /// <param name="name">name to be transformed</param>
    /// <returns></returns>
    public static string GetValidPascalCaseIdentifierName(string name) => SplitName(name)
        .Select(word => char.ToUpper(word[0]) + word.Substring(1))
        .Aggregate((previous, current) => previous + current);

    /// <summary>
    /// Returns a Snake Case format for given string.
    /// </summary>
    /// <param name="name">name to be transformed</param>
    /// <returns></returns>
    public static string GetUpperSnakeCasedIdentifierName(string name) => new(
        SplitName(name)
            .Select(word => char.ToUpper(word[0]) + word.Substring(1) + "_")
            .Aggregate((previous, current) => previous + current)
            .SkipLast(1)
            .ToArray()
        );

    public static string NormalizeLineEndings(this string text) =>
        LineEndings.Replace(text, Environment.NewLine);

    public static string GenerateCommentString(string customComment)
    {
        if (string.IsNullOrWhiteSpace(customComment))
        {
            throw new ArgumentNullException(nameof(customComment));
        }

        return
            @$"// <auto-generated>
// This code was generated by Kontent.ai model generator tool
// (see https://github.com/kontent-ai/dotnet/tree/main/src/model-generator).
//
{customComment}
// </auto-generated>{Environment.NewLine}{Environment.NewLine}";
    }

    public static string GetEnumerableType(string typeName) => string.IsNullOrWhiteSpace(typeName)
        ? throw new ArgumentException("", nameof(typeName))
        : $"{nameof(IEnumerable)}<{typeName}>";

    private static string[] SplitName(string name)
    {
        var sanitizedName = Regex.Replace(name, "[^a-zA-Z0-9]", WordSeparator, RegexOptions.IgnoreCase | RegexOptions.Multiline, RegexTimeout);

        // Remove leading numbers and leading whitespace (e.g.: '  123Name123' -> 'Name123'
        sanitizedName = Regex.Replace(sanitizedName, "^(\\s|[0-9])+", "", RegexOptions.None, RegexTimeout);

        if (sanitizedName == string.Empty)
        {
            throw new InvalidIdentifierException($"Unable to create a valid Identifier from '{name}'");
        }

        return sanitizedName
            .ToLower()
            .Split([WordSeparator], StringSplitOptions.RemoveEmptyEntries);
    }
}
